import { productType } from "@/Types/types";
import { PortableText } from "@portabletext/react";
import { PortableTextBlock } from "sanity";

export const productsMock: any = [
  {
    _id: "1",
    name: "Color 45 renew",
    color: ["#ffffff"],
    length: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    description: "",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    _createdAt: "",
    _updateAt: "",
    brand: "",
    stock: 0,
  },
  {
    _id: "1",
    name: "Color 45 renew",
    color: ["#ffffff"],
    length: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    description: "",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    _createdAt: "",
    _updateAt: "",
    brand: "",
    stock: 0,
  },
  {
    _id: "1",
    name: "Color 45 renew",
    color: ["#ffffff"],
    length: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    description: "",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    _createdAt: "",
    _updateAt: "",
    brand: "",
    stock: 0,
  },
  {
    _id: "1",
    name: "Color 45 renew",
    color: ["#ffffff"],
    length: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    description: "",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    _createdAt: "",
    _updateAt: "",
    brand: "",
    stock: 0,
  },
  {
    _id: "1",
    name: "Color 45 renew",
    color: ["#ffffff"],
    length: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    description: "",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    _createdAt: "",
    _updateAt: "",
    brand: "",
    stock: 0,
  },
];

export const initialFilterValues = {
  category: undefined,
  search: "",
  color: "",
  priceMin: 0,
  priceMax: 0,
  discount: 0,
};
export const categoriesFilter = [
  {
    name: "Nano Slim",
    value: "nano slim",
  },
  {
    name: "Ghana Weave",
    value: "ghana weave",
  },
];

export const colorFilter = [
  "#007273",
  "#000000",
  "#000666",
  "#8c59b4",
  "#ffffff",
  "#FDB29B",
];
