import { productType } from "@/Types/types";

export const productsMock: productType[] = [
  {
    id: "1",
    name: "Color 45 renew",
    color: "#ffffff",
    category: "nano slim",
    price: 400000,
    ratings: 4.3,
    image: "/hairs/hairOne.webp",
    discount: 0,
    createdAt: "",
    updateAt: "",
  },
  {
    id: "2",
    name: "Color 45 renew",
    color: "#ffffff",
    category: "ghana weave",
    price: 340000,
    ratings: 3.3,
    image: "/hairs/SUPERSOFT_480x.webp",
    discount: 30,
    createdAt: "",
    updateAt: "",
  },
  {
    id: "3",
    name: "Color 45 renew",
    color: "#ffffff",
    category: "ghana weave",
    price: 340000,
    ratings: 5,
    image: "/hairs/Darling-Empress-CurlyBraid-27_1024x1024.webp",
    discount: 0,
    createdAt: "",
    updateAt: "",
  },
  {
    id: "4",
    name: "Color 45 renew",
    color: "#ffffff",
    category: "nano slim",
    price: 400000,
    ratings: 4.5,
    image: "/hairs/hairOne.webp",
    discount: 0,
    createdAt: "",
    updateAt: "",
  },
  {
    id: "5",
    name: "Color 45 renew",
    color: "#ffffff",
    category: "ghana weave",
    price: 340000,
    ratings: 4.3,
    image: "/hairs/Easy-Braid-7X_1024x1024.webp",
    discount: 0,
    createdAt: "",
    updateAt: "",
  },
];
